from fastapi import FastAPI, Path
# We run our web server using uvicorn
# uvicorn myapi:app --reload # Command to run the uvicorn server
# AutoGenerated docs at /docs

app = FastAPI() # Create a FastAPI instance

# Endpoint methods
# GET - GET INFO
# POST - CREATE SOMETHING NEW
# PUT - UPDATE
# DELETE - DELETE SOMETHING 

students = {
    1: {
        "name": "John",
        "age": 17,
        "class": 12
    }
}

# Create new endpoint for home page
@app.get("/")
def index():
    return {"name": "First Data"}

# Path Pramaters (Variable Path)
# These are dynamic variable which can return aout dynamic results
# based on the input recieved
@app.get("/get-student/{student_id}")
def get_student(student_id: int = Path(None, description="The ID of the student you want to view")):
    return students[student_id]

# Path is used to add more descriptive style
# It shows up in the docs and also checks on the inputs recieved in the API parameter